# Generated by Django 2.2.13 on 2021-10-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211026_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
