version: '3'

services:
  # db:
  #   image: mysql:latest
  #   restart: always
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test
  #     MYSQL_USER: test
  #     MYSQL_DATABASE: test
  #     MYSQL_PASSWORD: test
  #   ports:
  #     - 3306:3306
  #   expose:
  #     - 3306
  #   volumes:
  #     - mysqldata:/var/lib/mysql
  #     - ./mysql/conf.d:/etc/mysql/conf.d
  #   command: --default-authentication-plugin=mysql_native_password

  web:
    container_name: django
    build: ./dockerfiles/django
    command:
      uwsgi --socket :8000 --http :8001  --module api.wsgi --py-autoreload 1 -b 32768
#      python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    # depends_on:
    #   - db

  front:
    container_name: nuxt
    build: ./dockerfiles/nuxt
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    tty: true
    command:
      npm run dev
    volumes:
      - ./client:/code
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.13
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
      - web
    ports:
      - "80:80"

# volumes:
#   mysqldata:

